services:
  - type: web
    name: yt-downloader-backend
    env: python
    rootDir: backend
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg nodejs npm
      pip install -r requirements.txt
    startCommand: gunicorn app:app
